# Generated by Django 2.2.16 on 2023-11-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dal', '0001_initial'),
    ]

    operations = [

        migrations.CreateModel(
            name='detects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detectid', models.CharField(max_length=32, unique=True)),
                ('detectcontent', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': '识别管理',
                'verbose_name_plural': '识别管理',
                'db_table': 'detectinfo',
            },
        ),
        migrations.CreateModel(
            name='garorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=32, unique=True)),
                ('ordercaptain', models.CharField(max_length=32, verbose_name='订单内容')),
            ],
            options={
                'verbose_name': '订单管理',
                'verbose_name_plural': '订单管理',
                'db_table': 'orderinfo',
            },
        )
    ]
