# Generated by Django 2.2.16 on 2023-11-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0003_auto_20231128_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detects',
            name='detectid',
        ),

        migrations.AddField(
            model_name='detects',
            name='detectresult',
            field=models.CharField(max_length=32),
            preserve_default=False,
        ),

    ]
