# Generated by Django 2.2.16 on 2023-11-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0004_auto_20231128_1358'),
    ]

    operations = [


    ]
