# Generated by Django 2.2.16 on 2023-11-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0005_auto_20231128_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detects',
            name='detectcontent',
            field=models.CharField(max_length=32),
        ),

    ]
