# Generated by Django 2.2.16 on 2023-11-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0006_auto_20231128_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=32, unique=True, verbose_name='教室')),
                ('time', models.DateTimeField(auto_now=True, null=True, verbose_name='教室添加时间')),
            ],
            options={
                'verbose_name': '教室管理',
                'verbose_name_plural': '教室管理',
                'db_table': 'ClassNames',
            },
        ),
        migrations.CreateModel(
            name='detectsjpg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detectcontent', models.CharField(max_length=32)),
                ('detectresult', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '识别图片管理',
                'verbose_name_plural': '识别图片管理',
                'db_table': 'detectjpginfo',
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsid', models.CharField(max_length=32, unique=True)),
                ('newscaptain', models.CharField(max_length=32, verbose_name='新闻标题')),
                ('newsdetail', models.CharField(max_length=32, verbose_name='新闻详情')),
                ('newsdate', models.CharField(max_length=32, verbose_name='新闻日期')),
            ],
            options={
                'verbose_name': '新闻管理',
                'verbose_name_plural': '新闻管理',
                'db_table': 'newsinfo',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=32, unique=True, verbose_name='教师')),
                ('subject_title', models.CharField(max_length=32, unique=True, verbose_name='课程名称')),
                ('introduction', models.CharField(max_length=640, verbose_name='课程简介')),
                ('time', models.DateTimeField(auto_now=True, null=True, verbose_name='课程创建时间')),
                ('startime', models.CharField(max_length=32, unique=True, verbose_name='上课时间')),
                ('class_name', models.ManyToManyField(to='dal.ClassNames', verbose_name='教室')),
            ],
            options={
                'verbose_name': '课表',
                'verbose_name_plural': '课表',
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('classname', models.CharField(max_length=64, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'UserInfo',
            },
        ),
        migrations.AlterModelOptions(
            name='detects',
            options={'verbose_name': '识别视频管理', 'verbose_name_plural': '识别视频管理'},
        ),
        migrations.CreateModel(
            name='TecInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='教师用户名')),
                ('name', models.CharField(max_length=32, verbose_name='教师姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('experience', models.CharField(max_length=32, verbose_name='经历')),
                ('style', models.CharField(max_length=32, verbose_name='授课风格')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('subject_title', models.ManyToManyField(to='dal.Subject', verbose_name='课程')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
                'db_table': 'TecInfo',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_student',
            field=models.ManyToManyField(to='dal.UserInfo', verbose_name='所选学生'),
        ),
        migrations.AddField(
            model_name='classnames',
            name='user',
            field=models.ManyToManyField(to='dal.UserInfo', verbose_name='教室学生'),
        ),
    ]
