# Generated by Django 2.2.16 on 2023-11-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0007_auto_20231128_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='garorder',
        ),
        migrations.DeleteModel(
            name='news',
        ),
    ]
